services:
  sql:
    build:
      context: .
      dockerfile: Dockerfile.sql
    container_name: bookstore-sql
    environment:
      SA_PASSWORD: 'P@ssw0rd123!'
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./init-db:/var/opt/mssql/backup

  web:
    build: .
    container_name: bookstore-web
    depends_on:
      - sql
    environment:
      ConnectionStrings__BookShopConnection: 'Server=sql,1433;Database=BookstoreDb;User Id=sa;Password=P@ssw0rd123!;TrustServerCertificate=True;'
    ports:
      - "8080:8080"
